// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3XUKGp4tEucKMvxSIf5Iu_SBIOGHquUE',
    appId: '1:484062529604:web:1b46c3ae21d3e8d0989411',
    messagingSenderId: '484062529604',
    projectId: 'eduapp-41260',
    authDomain: 'eduapp-41260.firebaseapp.com',
    storageBucket: 'eduapp-41260.firebasestorage.app',
    measurementId: 'G-GVDXVD03J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFEWLyzISMgnC5QjewNUcii1dXs2NMPmY',
    appId: '1:484062529604:android:a1cdcb00b1d84dbd989411',
    messagingSenderId: '484062529604',
    projectId: 'eduapp-41260',
    storageBucket: 'eduapp-41260.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmlM4lpTjBB2I23RqXZD170D8iPCzKAyI',
    appId: '1:484062529604:ios:9a8fd135ecf5de04989411',
    messagingSenderId: '484062529604',
    projectId: 'eduapp-41260',
    storageBucket: 'eduapp-41260.firebasestorage.app',
    iosClientId: '484062529604-vjepdut1i17q1656h5ai3q6kj4089b7n.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
